M3GUntextured:off
M3GWireframe:off
deleteTempKJXFiles:on
dumpAudioStreams:off
dumpGraphicsObjects:off
fpsCounterPosition:Off
input_ArrowDown:40
input_ArrowLeft:37
input_ArrowRight:39
input_ArrowUp:38
input_CLR:65
input_FastForward:32
input_Fire:10
input_LeftSoft:81
input_Num0:96
input_Num1:97
input_Num2:98
input_Num3:99
input_Num4:100
input_Num5:101
input_Num6:102
input_Num7:103
input_Num8:104
input_Num9:105
input_PauseResume:88
input_Pound:82
input_RightSoft:87
input_Screenshot:67
input_Star:69
logLevel:2
